consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  StudiouslyClass:
    description: StudiouslyClass media type (default view)
    example:
      current_unit: 4.8620256e+18
      id: 6.7972117e+18
      name: Blanditiis ipsum perferendis fugiat.
    properties:
      current_unit:
        description: Current unit of study
        example: 4.8620256e+18
        format: int64
        type: integer
      id:
        example: 6.7972117e+18
        format: int64
        type: integer
      name:
        example: Blanditiis ipsum perferendis fugiat.
        type: string
    required:
    - id
    - name
    title: 'Mediatype identifier: application/studiously.class+json; view=default'
    type: object
  StudiouslyClassCollection:
    description: StudiouslyClassCollection is the media type for an array of StudiouslyClass
      (default view)
    example:
    - current_unit: 4.8620256e+18
      id: 6.7972117e+18
      name: Blanditiis ipsum perferendis fugiat.
    - current_unit: 4.8620256e+18
      id: 6.7972117e+18
      name: Blanditiis ipsum perferendis fugiat.
    items:
      $ref: '#/definitions/StudiouslyClass'
    title: 'Mediatype identifier: application/studiously.class+json; type=collection;
      view=default'
    type: array
  StudiouslyMember:
    description: StudiouslyMember media type (default view)
    example:
      id: 3.7491802e+18
      name: Enim harum consequatur eum aut sint.
      role: student
    properties:
      id:
        example: 3.7491802e+18
        format: int64
        type: integer
      name:
        example: Enim harum consequatur eum aut sint.
        type: string
      role:
        enum:
        - student
        - moderator
        - teacher
        - administrator
        example: student
        type: string
    required:
    - id
    - name
    - role
    title: 'Mediatype identifier: application/studiously.member+json; view=default'
    type: object
  StudiouslyMemberCollection:
    description: StudiouslyMemberCollection is the media type for an array of StudiouslyMember
      (default view)
    example:
    - id: 3.7491802e+18
      name: Enim harum consequatur eum aut sint.
      role: student
    - id: 3.7491802e+18
      name: Enim harum consequatur eum aut sint.
      role: student
    items:
      $ref: '#/definitions/StudiouslyMember'
    title: 'Mediatype identifier: application/studiously.member+json; type=collection;
      view=default'
    type: array
  StudiouslyQuestion:
    description: StudiouslyQuestion media type (default view)
    example:
      answered: true
      author_id: 9.141401e+18
      data: 1995-04-24T16:02:00-05:00
      id: 9.057684e+18
      question_type: Commodi aperiam impedit dolores.
      unit_id: 3.5047505e+18
      votes: 2.8645733e+18
    properties:
      answered:
        example: true
        type: boolean
      author_id:
        example: 9.141401e+18
        format: int64
        type: integer
      data:
        example: 1995-04-24T16:02:00-05:00
      id:
        example: 9.057684e+18
        format: int64
        type: integer
      question_type:
        example: Commodi aperiam impedit dolores.
        type: string
      unit_id:
        example: 3.5047505e+18
        format: int64
        type: integer
      votes:
        example: 2.8645733e+18
        format: int64
        type: integer
    required:
    - id
    - question_type
    - unit_id
    title: 'Mediatype identifier: application/studiously.question+json; view=default'
    type: object
  StudiouslyQuestionFeed:
    description: StudiouslyQuestion media type (feed view)
    example:
      answered: true
      author_id: 9.141401e+18
      id: 9.057684e+18
      unit_id: 3.5047505e+18
      votes: 2.8645733e+18
    properties:
      answered:
        example: true
        type: boolean
      author_id:
        example: 9.141401e+18
        format: int64
        type: integer
      id:
        example: 9.057684e+18
        format: int64
        type: integer
      unit_id:
        example: 3.5047505e+18
        format: int64
        type: integer
      votes:
        example: 2.8645733e+18
        format: int64
        type: integer
    required:
    - id
    - unit_id
    title: 'Mediatype identifier: application/studiously.question+json; view=feed'
    type: object
  StudiouslyQuestionFeedCollection:
    description: StudiouslyQuestionFeedCollection is the media type for an array of
      StudiouslyQuestionFeed (default view)
    example:
    - answered: true
      author_id: 9.141401e+18
      data: 1995-04-24T16:02:00-05:00
      id: 9.057684e+18
      question_type: Commodi aperiam impedit dolores.
      unit_id: 3.5047505e+18
      votes: 2.8645733e+18
    items:
      $ref: '#/definitions/StudiouslyQuestionFeed'
    title: 'Mediatype identifier: application/studiously.question+json; type=collection;
      view=feed'
    type: array
host: localhost:8080
info:
  title: Studiously API
  version: ""
paths:
  /classes:
    get:
      description: Get all classes a user is in
      operationId: class#list
      produces:
      - application/studiously.class+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudiouslyClassCollection'
        "404":
          description: Class does not exist or the user does not have access to it
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: list class
      tags:
      - class
  /classes/{class_id}:
    get:
      description: Get class by ID
      operationId: class#show
      parameters:
      - description: Class ID
        in: path
        name: class_id
        required: true
        type: integer
      produces:
      - application/studiously.class+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudiouslyClass'
        "404":
          description: Class does not exist or the user does not have access to it
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show class
      tags:
      - class
  /classes/{class_id}/members:
    get:
      description: Get members of a class
      operationId: class#show_members
      parameters:
      - description: Class ID
        in: path
        name: class_id
        required: true
        type: integer
      produces:
      - application/studiously.member+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudiouslyMemberCollection'
        "404":
          description: Class does not exist or the user does not have access to it
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show_members class
      tags:
      - class
  /classes/{class_id}/questions:
    get:
      description: Get questions for a class
      operationId: class#show_questions
      parameters:
      - description: Filter by whether the question has been answered by the member
        in: query
        name: answered
        required: false
        type: boolean
      - description: Filter by author
        in: query
        name: author_id
        required: false
        type: integer
      - description: Class ID
        in: path
        name: class_id
        required: true
        type: integer
      - description: Filter by question type
        in: query
        name: question_type
        required: false
        type: string
      - description: Filter by unit
        in: query
        name: unit_id
        required: false
        type: integer
      produces:
      - application/studiously.question+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudiouslyQuestionFeedCollection'
        "400":
          description: A query parameter is invalid
        "404":
          description: Class does not exist or the user does not have access to it
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show_questions class
      tags:
      - class
  /questions/{questionID}:
    get:
      description: Get a question by ID
      operationId: question#show
      parameters:
      - description: Question ID
        in: path
        name: questionID
        required: true
        type: integer
      produces:
      - application/studiously.question+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/StudiouslyQuestion'
        "404":
          description: Question not found
        "500":
          description: Internal Server Error
      schemes:
      - http
      summary: show question
      tags:
      - question
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  InternalServerError:
    description: Internal Server Error
schemes:
- http
swagger: "2.0"
