// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "studiously": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/studiously/core/design
// --out=$(GOPATH)/src/github.com/studiously/core
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// ClassHref returns the resource href.
func ClassHref(classID interface{}) string {
	paramclassID := strings.TrimLeftFunc(fmt.Sprintf("%v", classID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/classes/%v", paramclassID)
}

// QuestionHref returns the resource href.
func QuestionHref(questionID interface{}) string {
	paramquestionID := strings.TrimLeftFunc(fmt.Sprintf("%v", questionID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/questions/%v", paramquestionID)
}
