// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "studiously": Application User Types
//
// Command:
// $ goagen
// --design=github.com/studiously/core/design
// --out=$(GOPATH)/src/github.com/studiously/core
// --version=v1.2.0-dirty

package app
